# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 07:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchschedule',
            name='branch',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='user.Branch'),
        ),
    ]
